#!/bin/bash

SERVER_HOST=@{{SERVER_HOST}}
USER_LOGIN=@{{SERVER_HOST}}

LOCAL_PLANE_DIR=@{{LOCAL_PLANE_DIR}}

REMOTE_PLANE_DIR=@{{REMOTE_PLANE_DIR}}

LOCAL_PLANE_DIR_PAGE=$LOCAL_PLANE_DIR/@{{PAGE_NAME_SRC}}

REMOTE_DIR_PAGE=$REMOTE_PLANE_DIR/@{{PAGE_NAME_DST}}

echo "COPY PAGES FROM $SERVER_HOST >>> $LOCAL_PLANE_DIR >>>>>>>>> $REMOTE_PLANE_DIR"

ssh $USER_LOGIN@$SERVER_HOST "rm -rf $REMOTE_DIR_PAGE"

sshpass -p $SERVERP scp -o StrictHostKeyChecking=no -r $LOCAL_PLANE_DIR_PAGE $USER_LOGIN@$SERVER_HOST:$REMOTE_DIR_PAGE

echo "file://$LOCAL_PLANE_DIR"
