/*
 * Superset
 * Superset
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package zk_os.sec;

import mpu.core.ARG;
import mpu.core.ARR;
import mpt.IaUser;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.security.authentication.AbstractAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.security.core.context.SecurityContextHolder;
import utl_rest.StatusException;
import zk_os.db.net.WebUsr;

import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

public class BeaAuth extends AbstractAuthenticationToken {

	public static final Logger L = LoggerFactory.getLogger(BeaAuth.class);

	//	public final WebUsr usr;
	private final WebUsr usr;

	public WebUsr webUsr() {
		return usr;
	}

	public BeaAuth(WebUsr usr, Collection<? extends GrantedAuthority> authorities) {
		super(authorities);
		this.usr = usr;
	}

	public static BeaAuth get(BeaAuth... defRq) {
		SecurityContext ctx = SecurityContextHolder.getContext();
		Authentication authentication = ctx.getAuthentication();
		if (authentication != null) {
			if (authentication instanceof BeaAuth) {
				return (BeaAuth) authentication;
			}
		}
		return Sec.returnDefOrThrow(defRq);
	}

	public static BeaAuth author(ROLE... roles) {
		BeaAuth tsmAuth = get();
		if (tsmAuth != null) {
			for (ROLE role : roles) {
				if (role.hasGaRole(tsmAuth)) {
					return tsmAuth;
				}
			}
		}
		throw StatusException.CODE(HttpStatus.FORBIDDEN);
	}

	public static BeaAuth of(WebUsr usr) {
		List<String> roles = usr.getRolesList();
		Collection<GrantedAuthority> gaRoles = roles.stream().map(ROLE::toGaRole).collect(Collectors.toList());
		return new BeaAuth(usr, gaRoles);
	}

//	public static WebUsr getSimpleUsrOr500(WebUsr... defRq) {
//		return getUsrOr401_500(false, defRq);
//	}

//	public static WebUsr getRootUsrOr500(WebUsr... defRq) {
//		return getUsrOr401_500(true, defRq);
//	}

//	public static WebUsr getUsrOr401_500(boolean isRootApp, WebUsr... defRq) {
//		WebUsr usr = getUsr(null);
//		boolean getIsRootAppUser = UsrSrv.isRootAppUser(usr);
//		if (usr != null && (isRootApp == getIsRootAppUser)) {
//			return usr;
//		} else if (ARG.isDef(defRq)) {
//			return ARG.toDef(defRq);
//		}
//		String err = usr == null ? "Undefined Usr" : (getIsRootAppUser ? "Except Common Usr" : "Except App Usr");
//		if (L.isErrorEnabled()) {
//			L.error(err + ":" + usr);
//		}
//		if (getIsRootAppUser) {
//			throw StatusException.C500(err);
//		} else {
//			throw StatusException.C401();
//		}
//	}

	public static WebUsr getUsr(WebUsr... defRq) {
		BeaAuth tsmAuth = get(null);
		if (tsmAuth != null) {
			return (WebUsr) tsmAuth.getPrincipal();
		}
		return ARG.toDefThrow("Auth is null", defRq);
	}

//	public static BeaAuth loadByUsr(long sid) {
//		BeaAuth tsmAuth = BeaAuth.of(WebUsr.byId(sid));
//		SecurityContextHolder.getContext().setAuthentication(tsmAuth);
//		return tsmAuth;
//	}

	public static BeaAuth fake(long sid, String name, boolean... updateSpringAuth) {
		WebUsr usr1 = new WebUsr();
		usr1.sid = sid;
		usr1.first_name = name;
		BeaAuth tsmAuth = new BeaAuth(usr1, ARR.as());
		if (ARG.isDefEqTrue(updateSpringAuth)) {
			SecurityContextHolder.getContext().setAuthentication(tsmAuth);
		}
		return tsmAuth;
	}

	public IaUser usr() {
		return usr;
	}

	@Override
	public Object getPrincipal() {
//		return US.joinNL(getAuthorities());
		return usr;
	}

	@Override
	public Object getCredentials() {
		return null;
	}


}