/*
 * Superset
 * Superset
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package zk_os.sec;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.authentication.AbstractAuthenticationToken;
import org.springframework.security.core.GrantedAuthority;
import zk_os.db.net.WebUsr;

import java.util.Collection;

public class ZAuth extends AbstractAuthenticationToken {

	public static final Logger L = LoggerFactory.getLogger(ZAuth.class);

	private final WebUsr usr;

	public WebUsr get() {
		return usr;
	}

	public ZAuth(WebUsr usr, Collection<? extends GrantedAuthority> authorities) {
		super(authorities);
		this.usr = usr;
	}

	public static ZAuth fake(long sid, String name) {
		return Sec.setAuthByUserSid_Fake(sid, name);
	}

	@Override
	public Object getPrincipal() {
//		return US.joinNL(getAuthorities());
		return usr;
	}

	@Override
	public Object getCredentials() {
		return null;
	}


}